.386
STACK  SEGMENT USE16 STACK
	   DB 200 DUP(0)
STACK  ENDS
DATA   SEGMENT USE16
BUF1   DB 0, 1, 2, 3, 4, 5, 6, 7, 8, 9;10 BYTE
BUF2   DB 10 DUP(0);10 BYTE
BUF3   DB 10 DUP(0);10 BYTE
BUF4   DB 10 DUP(0);10 BYTE
DATA   ENDS
CODE   SEGMENT USE16
	   ASSUME CS: CODE, DS: DATA, SS: STACK
START: MOV AX, DATA
       MOV DS, AX
       MOV ESI, OFFSET BUF1
	   ; MOV SI, OFFSET BUF1
	   ; MOV DI, OFFSET BUF2
	   ; MOV BX, OFFSET BUF3
	   ; MOV BP, OFFSET BUF4
	   MOV CX, 10
LOPA:  MOV AL, [ESI]
       MOV 10[ESI], AL
	   INC AL
	   MOV 20[ESI], AL
	   ADD AL, 3
	   MOV 30[ESI], AL
	   INC ESI
	   DEC CX
	   JNZ LOPA
	   MOV AH, 4CH
	   INT 21H
CODE   ENDS
       END START